[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shadowpay = "85nd28UHwfBzDcA9fRcCFjSGvdvvns7u7yxjcwVjuzpK"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
